name: biomarcadores
description: ""
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^6.0.1
  pedometer: ^4.0.1
  flutter_activity_recognition: ^4.0.0
  permission_handler: ^11.3.1
  sqflite: ^2.3.3+1
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  dio: ^5.4.0
  http: ^1.2.2
  shared_preferences: ^2.2.3
  intl_phone_field: ^3.2.0
  connectivity_plus: ^6.0.3
  jwt_decoder: ^2.0.1
  fl_chart: ^1.1.1
  google_fonts: ^7.0.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/Nodriza.png"
